[features]
seeds = false
skip-lint = false


# [programs.localnet]
# wifi_pass = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkgMQoezjZ8h1"

[programs.mainnet]
wifi_pass = "Ez6HvSNSd8kNrQLypWKaV694bkSeh9MjYWtWu6RYiftb"

[registry]
url = "https://api.apr.dev"



[provider]
cluster = "mainnet"
wallet = "~/.config/solana/mainnet-id.json" # Update this path to your mainnet wallet

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
